const products = [
  {
    id: 1,
    name: "Fresh Orange Juice (500ml)",
    price: 4.5,
    old: null,
    rating: 5,
    reviews: 78,
    category: "Juice",
    type: "Fresh",
    flavour: "Citrus",
    img: "https://images.unsplash.com/photo-1613478223719-2ab802602423?q=80&w=600&auto=format&fit=crop",
    desc: "Cold-pressed fresh orange juice with no added sugar."
  },
  {
    id: 2,
    name: "Apple Juice (1L)",
    price: 3.99,
    old: null,
    rating: 4,
    reviews: 54,
    category: "Juice",
    type: "Packaged",
    flavour: "Apple",
    img: "https://setiakart.in/wp-content/uploads/2023/10/apple-1.png",
    desc: "Filtered apple juice in a recyclable carton."
  },
  {
    id: 3,
    name: "Potato Chips (Salted) 150g",
    price: 2.5,
    old: null,
    rating: 4,
    reviews: 210,
    category: "Snacks",
    type: "Packaged",
    flavour: "Salted",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUjaCXAjRCs_gJhIb_Wcy5PLTgXCgUr_0T9A&s",
    desc: "Crispy potato chips, perfect for snacking."
  },
  {
    id: 4,
    name: "Murukku Mix (250g)",
    price: 3.0,
    old: null,
    rating: 4,
    reviews: 116,
    category: "Snacks",
    type: "Packaged",
    flavour: "Spiced",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2klNDNv6atDm5SvrPXS4TtHgXIOVDVgQwrA&s",
    desc: "Traditional savory crunchy murukku, ready to eat."
  },
  {
    id: 5,
    name: "Vanilla Ice Cream Tub (500ml)",
    price: 6.0,
    old: 7.5,
    rating: 5,
    reviews: 320,
    category: "Ice Cream",
    type: "Frozen",
    flavour: "Vanilla",
    img: "https://images.unsplash.com/photo-1570197788417-0e82375c9371?q=80&w=600&auto=format&fit=crop",
    desc: "Creamy vanilla ice cream made with real milk."
  },
  {
    id: 6,
    name: "Mango Sorbet (500ml)",
    price: 5.5,
    old: null,
    rating: 4,
    reviews: 88,
    category: "Ice Cream",
    type: "Frozen",
    flavour: "Mango",
    img: "https://images.unsplash.com/photo-1534706936160-d5ee67737249?q=80&w=600&auto=format&fit=crop",
    desc: "Refreshing dairy-free mango sorbet."
  },
  {
    id: 7,
    name: "Fresh Bananas (1kg)",
    price: 2.8,
    old: null,
    rating: 5,
    reviews: 142,
    category: "Fruits",
    type: "Fresh",
    flavour: "Sweet",
    img: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?q=80&w=600&auto=format&fit=crop",
    desc: "Ripe bananas, ideal for smoothies and snacks."
  },
  {
    id: 8,
    name: "Mixed Vegetables Pack (500g)",
    price: 3.5,
    old: null,
    rating: 4,
    reviews: 65,
    category: "Vegetables",
    type: "Fresh",
    flavour: "Mixed",
    img: "https://artcaffemarket.co.ke/cdn/shop/files/WhatsApp_Image_2025-08-20_at_12.17.33_9ed92636.jpg?v=1755739579",
    desc: "Fresh mixed vegetables, pre-washed and chopped for convenience."
  }
];